### ISSUE TITLE
Games crashes when wind turbine attempts to update as payload

### ISSUE THREAD

**Issue by Weathercold** [Slava0135/reVision#16]
Reproduce: put wind turbine on payload conveyor

Error:
```
java.lang.NullPointerException: Cannot invoke "mindustry.world.Tile.solid()" because the return value of "mindustry.core.World.tile(int, int)" is null
	at revision.world.blocks.power.WindTurbine$WindTurbineBuild.updateTile(WindTurbine.kt:64)
	at mindustry.gen.Building.update(Building.java:1207)
	at mindustry.world.blocks.payloads.BuildPayload.update(BuildPayload.java:45)
	at mindustry.world.blocks.payloads.PayloadBlock$PayloadBlockBuild.updateTile(PayloadBlock.java:141)
	at mindustry.world.blocks.payloads.PayloadSource$PayloadSourceBuild.updateTile(PayloadSource.java:117)
	at mindustry.gen.Building.update(Building.java:1207)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:59)
	at mindustry.gen.Groups.update(Groups.java:71)
	at mindustry.core.Logic.update(Logic.java:413)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:179)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:78)```

**Comment by Weathercold** [comment]
rip my save

**Comment by Slava0135** [comment]
latest v7 build?

**Comment by Weathercold** [comment]
yes

**Comment by Slava0135** [comment]
fixed
